Adapt create-kubeconfig to work with latest k8s version
After long-lived tokens are no longer created automatically

diff --git a/create-kubeconfig b/create-kubeconfig
--- a/create-kubeconfig
+++ b/create-kubeconfig
@@ -9,7 +9,7 @@
 set -e
 
 if [[ $# == 0 ]]; then
-  echo "Usage: $0 SERVICEACCOUNT [kubectl options]" >&2
+  echo "Usage: $0 [SECRET of type kubernetes.io/service-account-token] [kubectl options]" >&2
   echo "" >&2
   echo "This script creates a kubeconfig to access the apiserver with the specified serviceaccount and outputs it to stdout." >&2
 
@@ -20,16 +20,16 @@ function _kubectl() {
   kubectl $@ $kubectl_options
 }
 
-serviceaccount="$1"
+secret="$1"
 kubectl_options="${@:2}"
 
-if ! secret="$(_kubectl get serviceaccount "$serviceaccount" -o 'jsonpath={.secrets[0].name}' 2>/dev/null)"; then
-  echo "serviceaccounts \"$serviceaccount\" not found." >&2
+if ! type="$(_kubectl get secret "$secret"  -o jsonpath='{.type}' 2>/dev/null)"; then
+  echo "secret \"$secret\" not found." >&2
   exit 2
 fi
 
-if [[ -z "$secret" ]]; then
-  echo "serviceaccounts \"$serviceaccount\" doesn't have a serviceaccount token." >&2
+if [[ "$type" != 'kubernetes.io/service-account-token' ]]; then
+  echo "secret  \"$secret\" is not a service-account-token." >&2
   exit 2
 fi
 
@@ -42,10 +42,11 @@ server="$(_kubectl config view -o "jsonpath={.clusters[?(@.name==\"$cluster\")].
 ca_crt_data="$(_kubectl get secret "$secret" -o "jsonpath={.data.ca\.crt}" | openssl enc -d -base64 -A)"
 namespace="$(_kubectl get secret "$secret" -o "jsonpath={.data.namespace}" | openssl enc -d -base64 -A)"
 token="$(_kubectl get secret "$secret" -o "jsonpath={.data.token}" | openssl enc -d -base64 -A)"
+serviceaccount="$(_kubectl get secret "$secret" -o jsonpath='{.metadata.annotations.kubernetes\.io/service-account\.name}')"
 
 export KUBECONFIG="$(mktemp)"
 kubectl config set-credentials "$serviceaccount" --token="$token" >/dev/null
-ca_crt="$(mktemp)"; echo "$ca_crt_data" > $ca_crt
+ca_crt="$(mktemp)"; echo "$ca_crt_data" > "$ca_crt"
 kubectl config set-cluster "$cluster" --server="$server" --certificate-authority="$ca_crt" --embed-certs >/dev/null
 kubectl config set-context "$context" --cluster="$cluster" --namespace="$namespace" --user="$serviceaccount" >/dev/null
 kubectl config use-context "$context" >/dev/null
